[package]
name = "rust-study"
version = "0.1.0"
authors = ["龙云 <longyun@co-mall.com>"]

[dependencies]
hello_macro = { path = "./hello_macro" }
hello_macro_derive = { path = "./hello_macro/hello_macro_derive" }
rand ="0.3.14"